---
- name: Deploy NGINX with custom webinar page
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Apply Kubernetes resources (Namespace, ConfigMap, Deployment, Service)
      kubernetes.core.k8s:
        state: present
        definition:
          # 1) Namespace
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: aap-deploy

          # 2) ConfigMap with custom index.html
          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: nginx-index
              namespace: aap-deploy
            data:
              index.html: |
                <!DOCTYPE html>
                <html lang="en">
                <head>
                  <meta charset="UTF-8">
                  <title>Ansible Automation Platform Webinar</title>
                  <style>
                    body { font-family: Arial, sans-serif; background: #f4f6f8; text-align: center; padding-top: 80px; }
                    h1 { color: #c00; }
                    p  { font-size: 18px; color: #333; max-width: 900px; margin: 18px auto; line-height: 1.5; }
                    .box { background: #fff; display: inline-block; padding: 22px 26px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,.08); }
                    footer { margin-top: 40px; color: #666; font-size: 14px; }
                    ul { text-align: left; display: inline-block; margin: 12px auto 0; }
                  </style>
                </head>
                <body>
                  <div class="box">
                    <h1>Welcome to our webinar</h1>

                    <p>
                      <strong>Operate and Manage Automation with Ansible Automation Platform on Large-Scale Infrastructure</strong>
                    </p>

                    <p>
                      In this session, we’ll cover how to industrialize automation with governance, security, and reliability.
                      You’ll see practical patterns to run automation safely across hybrid environments (on-prem, cloud, and Kubernetes).
                    </p>

                    <p><strong>Agenda highlights:</strong></p>
                    <ul>
                      <li>Automation Controller concepts: Projects, Inventories, Credentials, Templates</li>
                      <li>Execution Environments for consistent, scalable runtimes</li>
                      <li>RBAC, approvals, and auditability at scale</li>
                      <li>Operational practices: monitoring, troubleshooting, and repeatability</li>
                      <li>Kubernetes integration: deploying and managing manifests with Ansible</li>
                    </ul>

                    <footer>
                      Powered by Ansible Automation Platform
                    </footer>
                  </div>
                </body>
                </html>

          # 3) Deployment
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: nginx
              namespace: aap-deploy
              labels:
                app: nginx
            spec:
              replicas: 2
              selector:
                matchLabels:
                  app: nginx
              template:
                metadata:
                  labels:
                    app: nginx
                spec:
                  containers:
                    - name: nginx
                      image: nginx:1.25
                      ports:
                        - containerPort: 80
                      volumeMounts:
                        - name: web-content
                          mountPath: /usr/share/nginx/html/index.html
                          subPath: index.html
                  volumes:
                    - name: web-content
                      configMap:
                        name: nginx-index

          # 4) Service
          - apiVersion: v1
            kind: Service
            metadata:
              name: nginx
              namespace: aap-deploy
            spec:
              selector:
                app: nginx
              ports:
                - port: 80
                  targetPort: 80
              type: ClusterIP
