---
- name: Deploy Application using NGINX page and expose via NodePort
  hosts: localhost
  gather_facts: false
  vars:
    namespace: aap-deploy
  tasks:
    - name: Apply Kubernetes resources (Namespace, ConfigMap, Deployment, NodePort Service)
      kubernetes.core.k8s:
        state: present
        definition:

          # 2) ConfigMap – custom NGINX web page
          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: nginx-index
              namespace: "{{ namespace }}"
            data:
              index.html: |
                <!DOCTYPE html>
                <html lang="fr">
                <head>
                  <meta charset="UTF-8" />
                  <meta name="viewport" content="width=device-width, initial-scale=1" />
                  <title>Formation — Déployer Kubernetes avec Ansible Automation Platform</title>
                  <style>
                    :root{
                      --bg:#ffffff;
                      --text:#111827;
                      --muted:#6b7280;
                      --line:#e5e7eb;
                      --card:#f9fafb;
                      --accent:#d62828;
                      --accent2:#111827;
                    }
                    *{box-sizing:border-box}
                    body{
                      margin:0;
                      font-family: Arial, Helvetica, sans-serif;
                      color:var(--text);
                      background:var(--bg);
                      line-height:1.55;
                    }
                    .wrap{
                      max-width: 1100px;
                      margin: 0 auto;
                      padding: 48px 18px;
                    }
                    header{
                      border:1px solid var(--line);
                      background:linear-gradient(180deg, #ffffff 0%, #fafafa 100%);
                      border-radius:16px;
                      padding:28px 22px;
                    }
                    .badge{
                      display:inline-block;
                      font-size:12px;
                      letter-spacing:.08em;
                      text-transform:uppercase;
                      color:var(--accent2);
                      border:1px solid var(--line);
                      border-radius:999px;
                      padding:6px 10px;
                      background:#fff;
                    }
                    h1{
                      margin:14px 0 8px;
                      font-size: clamp(26px, 3.2vw, 40px);
                      line-height:1.15;
                    }
                    .subtitle{
                      margin:0;
                      color:var(--muted);
                      font-size: 16px;
                      max-width: 880px;
                    }
                    .cta-row{
                      display:flex;
                      gap:12px;
                      flex-wrap:wrap;
                      margin-top:18px;
                    }
                    .btn{
                      display:inline-block;
                      padding:10px 14px;
                      border-radius:10px;
                      text-decoration:none;
                      border:1px solid var(--line);
                      color:var(--text);
                      background:#fff;
                      font-weight:600;
                    }
                    .btn.primary{
                      border-color:transparent;
                      background:var(--accent);
                      color:#fff;
                    }
                    .grid{
                      display:grid;
                      grid-template-columns: 1fr;
                      gap:14px;
                      margin-top:18px;
                    }
                    @media (min-width: 900px){
                      .grid{ grid-template-columns: 1.2fr .8fr; }
                    }
                    .card{
                      border:1px solid var(--line);
                      background:var(--card);
                      border-radius:16px;
                      padding:18px;
                    }
                    h2{
                      margin:0 0 10px;
                      font-size:18px;
                    }
                    ul{ margin: 10px 0 0 18px; padding:0; }
                    li{ margin: 6px 0; }
                    .kpis{
                      display:grid;
                      grid-template-columns: repeat(2, minmax(0, 1fr));
                      gap:10px;
                      margin-top:12px;
                    }
                    .kpi{
                      border:1px solid var(--line);
                      background:#fff;
                      border-radius:14px;
                      padding:12px;
                    }
                    .kpi .label{ font-size:12px; color:var(--muted); text-transform:uppercase; letter-spacing:.06em; }
                    .kpi .value{ font-size:16px; font-weight:700; margin-top:4px; }
                    .section{
                      margin-top:14px;
                    }
                    .timeline{
                      border-left:3px solid var(--line);
                      padding-left:12px;
                      margin-top:10px;
                    }
                    .step{
                      margin: 12px 0;
                      padding: 10px 12px;
                      border:1px solid var(--line);
                      background:#fff;
                      border-radius:12px;
                    }
                    .step .title{
                      font-weight:700;
                      margin-bottom:4px;
                    }
                    .note{
                      margin-top:10px;
                      color:var(--muted);
                      font-size:14px;
                    }
                    footer{
                      margin-top:18px;
                      padding-top:14px;
                      border-top:1px solid var(--line);
                      color:var(--muted);
                      font-size:13px;
                      display:flex;
                      justify-content:space-between;
                      flex-wrap:wrap;
                      gap:10px;
                    }
                    code{
                      font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
                      font-size: 12px;
                      background:#fff;
                      border:1px solid var(--line);
                      padding:2px 6px;
                      border-radius:8px;
                    }
                  </style>
                </head>
                <body>
                  <div class="wrap">
                    <header>
                      <span class="badge">Formation Hands-on • Kubernetes + AAP 2.6</span>
                      <h1>Déployer Kubernetes avec Ansible Automation Platform 2.6<br/>comme en production</h1>
                      <p class="subtitle">
                        Une formation pratique pour <strong>Plateforme Engineers</strong>, <strong>SRE</strong> et DevOps :
                        architecture, flux CI/CD, bonnes pratiques, et déploiements reproductibles sur un cluster Kubernetes.
                      </p>
                
                      <div class="cta-row">
                        <a class="btn primary" href="#programme">Voir le programme</a>
                        <a class="btn" href="#prerequis">Prérequis</a>
                        <a class="btn" href="#lab">Infos lab</a>
                      </div>
                    </header>
                
                    <div class="grid">
                      <section class="card">
                        <h2>Objectifs</h2>
                        <ul>
                          <li>Mettre en place un flux <strong>GitOps / automation</strong> avec Ansible Automation Platform 2.6.</li>
                          <li>Déployer des ressources Kubernetes (Namespace, Deployments, Services, Ingress, ConfigMaps, Secrets).</li>
                          <li>Industrialiser : variables, inventaires, environnements d’exécution, policies, RBAC, audit.</li>
                          <li>Appliquer les pratiques <strong>SRE</strong> : fiabilité, idempotence, rollback, observabilité.</li>
                        </ul>
                
                        <div class="kpis">
                          <div class="kpi">
                            <div class="label">Format</div>
                            <div class="value">Workshop / Lab</div>
                          </div>
                          <div class="kpi">
                            <div class="label">Niveau</div>
                            <div class="value">Intermédiaire → Avancé</div>
                          </div>
                          <div class="kpi">
                            <div class="label">Cible</div>
                            <div class="value">Plateforme Engineer, SRE, DevOps</div>
                          </div>
                          <div class="kpi">
                            <div class="label">Stack</div>
                            <div class="value">AAP 2.6 • Kubernetes • Git</div>
                          </div>
                        </div>
                
                        <p class="note">
                          Astuce : ce template HTML est pensé pour être servi via un <code>ConfigMap</code> (Nginx/HTTPD) sur Kubernetes.
                        </p>
                      </section>
                
                      <aside class="card">
                        <h2>Informations rapides</h2>
                        <ul>
                          <li><strong>Plateforme</strong> : Ansible Automation Platform 2.6</li>
                          <li><strong>Cluster</strong> : Kubernetes / OpenShift (compatible)</li>
                          <li><strong>Sources</strong> : Projet Git + templates AAP</li>
                          <li><strong>Livrables</strong> : playbooks, manifests, pipeline, runbooks</li>
                        </ul>
                
                        <div class="section" id="lab">
                          <h2>Lab (exemple)</h2>
                          <ul>
                            <li>1 VM AAP 2.6 + accès Automation Controller</li>
                            <li>1 cluster Kubernetes + kubeconfig</li>
                            <li>1 repo Git (playbooks + manifests)</li>
                          </ul>
                        </div>
                      </aside>
                    </div>
                
                    <section class="card section" id="programme">
                      <h2>Programme</h2>
                      <div class="timeline">
                        <div class="step">
                          <div class="title">1) Architecture AAP 2.6 & flux “production-grade”</div>
                          <div class="desc">Composants, RBAC, projets, credentials, inventory, templates, audit et bonnes pratiques d’exploitation.</div>
                        </div>
                        <div class="step">
                          <div class="title">2) Environnements d’exécution & collections Kubernetes</div>
                          <div class="desc">Construire/publier un Execution Environment, valider les dépendances, sécuriser les images.</div>
                        </div>
                        <div class="step">
                          <div class="title">3) Déployer sur Kubernetes avec Ansible</div>
                          <div class="desc">Manifests + module Kubernetes, variables par environnement, idempotence et stratégies de rollback.</div>
                        </div>
                        <div class="step">
                          <div class="title">4) Orchestration & industrialisation</div>
                          <div class="desc">Workflows, approvals, promotion dev→prod, gestion des secrets, standardisation des playbooks.</div>
                        </div>
                        <div class="step">
                          <div class="title">5) SRE : fiabilité, observabilité et runbooks</div>
                          <div class="desc">Monitoring, logs, alerting, post-mortems, runbooks d’automatisation, gestion des incidents.</div>
                        </div>
                      </div>
                    </section>
                
                    <section class="card section" id="prerequis">
                      <h2>Prérequis</h2>
                      <ul>
                        <li>Connaissances de base Kubernetes (Pods, Deployments, Services, Namespaces).</li>
                        <li>Notions Ansible (playbook, tasks, vars) + Git.</li>
                        <li>Accès à un cluster (kubeconfig) + droits suffisants (idéalement namespace dédié).</li>
                      </ul>
                      <p class="note">
                        Besoin d’un format “débutant” ? Remplace ce programme par une version “K8s basics + AAP basics” avant le lab.
                      </p>
                    </section>
                
                    <footer>
                      <div>© <span id="year"></span> — Formation Kubernetes avec Ansible Automation Platform 2.6</div>
                      <div>Contact : <strong>à renseigner</strong> • Lieu : <strong>à renseigner</strong></div>
                    </footer>
                  </div>
                
                  <script>
                    // Petite touche pour afficher l'année automatiquement (optionnel).
                    document.getElementById("year").textContent = new Date().getFullYear();
                  </script>
                </body>
                </html>




          # 3) Deployment
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: nginx
              namespace: "{{ namespace }}"
              labels:
                app: nginx
            spec:
              replicas: 2
              selector:
                matchLabels:
                  app: nginx
              template:
                metadata:
                  labels:
                    app: nginx
                spec:
                  containers:
                    - name: nginx
                      image: nginx:1.25
                      ports:
                        - containerPort: 80
                      volumeMounts:
                        - name: web-content
                          mountPath: /usr/share/nginx/html/index.html
                          subPath: index.html
                  volumes:
                    - name: web-content
                      configMap:
                        name: nginx-index

          # 4) NodePort Service
          - apiVersion: v1
            kind: Service
            metadata:
              name: nginx
              namespace: "{{ namespace }}"
            spec:
              type: NodePort
              selector:
                app: nginx
              ports:
                - name: http
                  port: 80
                  targetPort: 80
                  nodePort: 30080   # optional; must be within 30000–32767
        
        # kubectl command to port-forward:
        # kubectl -n "{{ namespace }}" port-forward svc/nginx 8080:
    #- name: kubectl port-forward
    #  ansible.builtin.command: >
    #    kubectl -n "{{ namespace }}" port-forward svc/nginx 8087:80
    #  register: port_forward_result

    #- name: Display port-forward result
    #  ansible.builtin.debug:
    #    var: port_forward_result.stdout
    #  