---
- name: Deploy NGINX webinar page via NodePort
  hosts: localhost
  gather_facts: false
  vars:
    namespace: aap-deploy
  tasks:
    - name: Apply Kubernetes resources (Namespace, ConfigMap, Deployment, NodePort Service)
      kubernetes.core.k8s:
        state: present
        definition:

          # 1) Namespace
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: "{{ namespace }}"

          # 2) ConfigMap – custom NGINX web page
          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: nginx-index
              namespace: "{{ namespace }}"
            data:
              index.html: |
                <!DOCTYPE html>
                <html lang="en">
                <head>
                  <meta charset="UTF-8" />
                  <title>Operate & Govern Automation at Scale | Webinar</title>
                
                  <meta name="viewport" content="width=device-width, initial-scale=1.0">
                
                  <style>
                    :root {
                      --bg-dark: #0b0e14;
                      --bg-card: #141824;
                      --primary: #22c55e;
                      --text-main: #ffffff;
                      --text-muted: #a1a1aa;
                      --accent: #6366f1;
                    }
                
                    * {
                      box-sizing: border-box;
                    }
                
                    body {
                      margin: 0;
                      font-family: "Segoe UI", Roboto, Arial, sans-serif;
                      background: radial-gradient(circle at top, #111827, var(--bg-dark));
                      color: var(--text-main);
                      line-height: 1.6;
                    }
                
                    .container {
                      max-width: 1200px;
                      margin: auto;
                      padding: 60px 24px;
                    }
                
                    /* HERO */
                    .hero {
                      display: grid;
                      grid-template-columns: 1.2fr 1fr;
                      gap: 48px;
                      align-items: center;
                    }
                
                    .hero h1 {
                      font-size: 44px;
                      line-height: 1.2;
                      margin-bottom: 20px;
                    }
                
                    .hero h1 span {
                      color: var(--primary);
                    }
                
                    .hero p {
                      color: var(--text-muted);
                      font-size: 18px;
                      max-width: 520px;
                    }
                
                    .badge {
                      display: inline-block;
                      background: rgba(34, 197, 94, 0.15);
                      color: var(--primary);
                      padding: 6px 14px;
                      border-radius: 20px;
                      font-size: 14px;
                      margin-bottom: 16px;
                    }
                
                    .hero img {
                      width: 100%;
                      border-radius: 16px;
                      box-shadow: 0 30px 80px rgba(0,0,0,0.6);
                    }
                
                    /* INFO CARDS */
                    .info {
                      display: grid;
                      grid-template-columns: repeat(3, 1fr);
                      gap: 20px;
                      margin-top: 60px;
                    }
                
                    .card {
                      background: var(--bg-card);
                      padding: 24px;
                      border-radius: 14px;
                      text-align: center;
                    }
                
                    .card h3 {
                      color: var(--primary);
                      margin-bottom: 6px;
                    }
                
                    /* SPEAKERS */
                    .speakers {
                      margin-top: 80px;
                    }
                
                    .speakers h2 {
                      font-size: 32px;
                      margin-bottom: 40px;
                      text-align: center;
                    }
                
                    .speaker-grid {
                      display: grid;
                      grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
                      gap: 32px;
                    }
                
                    .speaker {
                      background: var(--bg-card);
                      border-radius: 16px;
                      padding: 28px;
                      text-align: center;
                    }
                
                    .speaker img {
                      width: 120px;
                      height: 120px;
                      object-fit: cover;
                      border-radius: 50%;
                      margin-bottom: 16px;
                      border: 3px solid var(--accent);
                    }
                
                    .speaker h3 {
                      margin-bottom: 6px;
                    }
                
                    .speaker p {
                      font-size: 14px;
                      color: var(--text-muted);
                    }
                
                    /* FOOTER */
                    footer {
                      margin-top: 100px;
                      text-align: center;
                      color: var(--text-muted);
                      font-size: 14px;
                    }
                
                    @media (max-width: 900px) {
                      .hero {
                        grid-template-columns: 1fr;
                        text-align: center;
                      }
                
                      .hero p {
                        margin: auto;
                      }
                    }
                  </style>
                </head>
                
                <body>
                
                  <div class="container">
                
                    <!-- HERO SECTION -->
                    <section class="hero">
                      <div>
                        <div class="badge">FREE LIVE WEBINAR</div>
                        <h1>
                          Operate & Govern <span>Automation</span><br>
                          at Large Scale
                        </h1>
                
                        <p>
                          Discover how <strong>Ansible Automation Platform</strong> enables
                          enterprise-grade automation with governance, security, and operational
                          excellence across large-scale infrastructures.
                        </p>
                      </div>
                
                      <!-- MAIN IMAGE -->
                    </section>
                
                    <!-- INFO -->
                    <section class="info">
                      <div class="card">
                        <h3>Date</h3>
                        <p>08 January 2026</p>
                      </div>
                
                      <div class="card">
                        <h3>Time</h3>
                        <p>21:00 (Paris)</p>
                      </div>
                
                      <div class="card">
                        <h3>Format</h3>
                        <p>Online – Live Session</p>
                      </div>
                    </section>
                
                    <!-- SPEAKERS -->
                    <section class="speakers">
                      <h2>Speakers</h2>
                
                      <div class="speaker-grid">
                
                        <div class="speaker">
                          <h3>Florient Dogbe</h3>
                          <p>
                            MSc DevOps / Cloud Consultant<br>
                            RHCA, RHCOA, CKAD, CKA, Terraform, Azure, CEH
                          </p>
                        </div>
                
                        <div class="speaker">
                          <h3>Armel Ngando</h3>
                          <p>
                            Founder – teachmemore.fr<br>
                            Automation & Cloud Evangelist
                          </p>
                        </div>
                
                      </div>
                    </section>
                
                    <footer>
                      © 2026 TeachMeMore — Automation at Enterprise Scale
                    </footer>
                
                  </div>
                
                </body>
                </html>


          # 3) Deployment
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: nginx
              namespace: "{{ namespace }}"
              labels:
                app: nginx
            spec:
              replicas: 2
              selector:
                matchLabels:
                  app: nginx
              template:
                metadata:
                  labels:
                    app: nginx
                spec:
                  containers:
                    - name: nginx
                      image: nginx:1.25
                      ports:
                        - containerPort: 80
                      volumeMounts:
                        - name: web-content
                          mountPath: /usr/share/nginx/html/index.html
                          subPath: index.html
                  volumes:
                    - name: web-content
                      configMap:
                        name: nginx-index

          # 4) NodePort Service
          - apiVersion: v1
            kind: Service
            metadata:
              name: nginx
              namespace: "{{ namespace }}"
            spec:
              type: NodePort
              selector:
                app: nginx
              ports:
                - name: http
                  port: 80
                  targetPort: 80
                  nodePort: 30080   # optional; must be within 30000–32767
        
        # kubectl command to port-forward:
        # kubectl -n "{{ namespace }}" port-forward svc/nginx 8080:
    #- name: kubectl port-forward
    #  ansible.builtin.command: >
    #    kubectl -n "{{ namespace }}" port-forward svc/nginx 8087:80
    #  register: port_forward_result

    #- name: Display port-forward result
    #  ansible.builtin.debug:
    #    var: port_forward_result.stdout
    #  