---
- name: Deploy demo app with NGINX Ingress + cert-manager TLS
  hosts: localhost
  gather_facts: false

  vars:
    namespace: aap-deploy
    app_name: nginx
    ingress_class: nginx

    # Change this to your real DNS name that points to your ingress controller entrypoint
    host_fqdn: demo.example.com

    # cert-manager ClusterIssuer already created in your cluster (example: letsencrypt-prod)
    cluster_issuer: letsencrypt-prod

    # The secret cert-manager will create in the namespace
    tls_secret_name: demo-example-com-tls

  tasks:
    - name: Apply Kubernetes resources (Namespace, ConfigMap, Deployment, Service, Ingress)
      kubernetes.core.k8s:
        state: present
        definition:

          # 1) Namespace
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: "{{ namespace }}"

          # 2) ConfigMap – custom web page
          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: "{{ app_name }}-index"
              namespace: "{{ namespace }}"
            data:
              index.html: |
                <!DOCTYPE html>
                <html lang="en">
                <head>
                  <meta charset="UTF-8">
                  <title>Ansible Automation Platform Webinar</title>
                  <style>
                    body { font-family: Arial, sans-serif; background: #f4f6f8; text-align: center; padding-top: 80px; }
                    h1 { color: #c00; }
                    p  { font-size: 18px; color: #333; max-width: 900px; margin: 18px auto; line-height: 1.5; }
                    ul { text-align: left; display: inline-block; margin-top: 12px; }
                    footer { margin-top: 40px; color: #666; font-size: 14px; }
                  </style>
                </head>
                <body>
                  <h1>Welcome to our webinar</h1>

                  <p>
                    <strong>
                      Operate and Manage Automation with Ansible Automation Platform on Large-Scale Infrastructure
                    </strong>
                  </p>

                  <p>
                    In this session, we demonstrate how to build, govern, and operate automation at scale with Ansible
                    Automation Platform—covering execution environments, controller workflows, RBAC, credential management,
                    and reliable operations across hybrid infrastructures.
                  </p>

                  <p><strong>Topics covered:</strong></p>
                  <ul>
                    <li>Automation Controller: Projects, Inventories, Credentials, Templates</li>
                    <li>Execution Environments for consistent runtime dependencies</li>
                    <li>RBAC, auditing, and secure automation practices</li>
                    <li>Kubernetes automation: deploying and managing manifests with Ansible</li>
                    <li>Operational best practices for large-scale automation</li>
                  </ul>

                  <footer>
                    Powered by Ansible Automation Platform
                  </footer>
                </body>
                </html>

          # 3) Deployment
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: "{{ app_name }}"
              namespace: "{{ namespace }}"
              labels:
                app: "{{ app_name }}"
            spec:
              replicas: 2
              selector:
                matchLabels:
                  app: "{{ app_name }}"
              template:
                metadata:
                  labels:
                    app: "{{ app_name }}"
                spec:
                  containers:
                    - name: nginx
                      image: nginx:1.25
                      ports:
                        - containerPort: 80
                      readinessProbe:
                        httpGet:
                          path: /
                          port: 80
                        initialDelaySeconds: 3
                        periodSeconds: 10
                      livenessProbe:
                        httpGet:
                          path: /
                          port: 80
                        initialDelaySeconds: 10
                        periodSeconds: 20
                      volumeMounts:
                        - name: web-content
                          mountPath: /usr/share/nginx/html/index.html
                          subPath: index.html
                  volumes:
                    - name: web-content
                      configMap:
                        name: "{{ app_name }}-index"

          # 4) Service (ClusterIP; ingress routes to it)
          - apiVersion: v1
            kind: Service
            metadata:
              name: "{{ app_name }}"
              namespace: "{{ namespace }}"
            spec:
              selector:
                app: "{{ app_name }}"
              ports:
                - name: http
                  port: 80
                  targetPort: 80
              type: ClusterIP

          # 5) Ingress with cert-manager TLS
          - apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: "{{ app_name }}-ingress"
              namespace: "{{ namespace }}"
              annotations:
                # cert-manager will watch this and create a Certificate for the tls_secret_name
                cert-manager.io/cluster-issuer: "{{ cluster_issuer }}"
            spec:
              ingressClassName: "{{ ingress_class }}"
              tls:
                - hosts:
                    - "{{ host_fqdn }}"
                  secretName: "{{ tls_secret_name }}"
              rules:
                - host: "{{ host_fqdn }}"
                  http:
                    paths:
                      - path: /
                        pathType: Prefix
                        backend:
                          service:
                            name: "{{ app_name }}"
                            port:
                              number: 80

    - name: Show useful follow-up commands
      ansible.builtin.debug:
        msg:
          - "Check ingress: kubectl -n {{ namespace }} get ingress {{ app_name }}-ingress"
          - "Check cert:    kubectl -n {{ namespace }} get certificate,order,challenge"
          - "Check svc:     kubectl -n {{ namespace }} get svc {{ app_name }}"
          - "Access URL:    https://{{ host_fqdn }}/"
