---
- name: Deploy NGINX webinar page via NodePort
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Apply Kubernetes resources (Namespace, ConfigMap, Deployment, NodePort Service)
      kubernetes.core.k8s:
        state: present
        definition:

          # 1) Namespace
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: aap-deploy

          # 2) ConfigMap – custom NGINX web page
          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: nginx-index
              namespace: aap-deploy
            data:
              index.html: |
                <!DOCTYPE html>
                <html lang="en">
                <head>
                  <meta charset="UTF-8">
                  <title>Ansible Automation Platform Webinar</title>
                  <style>
                    body { font-family: Arial, sans-serif; background: #f4f6f8; text-align: center; padding-top: 80px; }
                    h1 { color: #c00; }
                    p  { font-size: 18px; color: #333; max-width: 900px; margin: 18px auto; line-height: 1.5; }
                    ul { text-align: left; display: inline-block; margin-top: 12px; }
                    footer { margin-top: 40px; color: #666; font-size: 14px; }
                  </style>
                </head>
                <body>
                  <h1>Welcome to our webinar</h1>

                  <p>
                    <strong>
                      Operate and Manage Automation with Ansible Automation Platform
                      on Large-Scale Infrastructure
                    </strong>
                  </p>

                  <p>
                    This session demonstrates how to run enterprise-grade automation
                    at scale using Ansible Automation Platform, with a strong focus on
                    governance, security, and operational excellence.
                  </p>

                  <p><strong>Topics covered:</strong></p>
                  <ul>
                    <li>Automation Controller architecture and workflows</li>
                    <li>Execution Environments for consistent automation</li>
                    <li>Credential and RBAC management</li>
                    <li>Kubernetes integration and Day-2 operations</li>
                  </ul>

                  <footer>
                    Powered by Ansible Automation Platform
                  </footer>
                </body>
                </html>

          # 3) Deployment
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: nginx
              namespace: aap-deploy
              labels:
                app: nginx
            spec:
              replicas: 2
              selector:
                matchLabels:
                  app: nginx
              template:
                metadata:
                  labels:
                    app: nginx
                spec:
                  containers:
                    - name: nginx
                      image: nginx:1.25
                      ports:
                        - containerPort: 80
                      volumeMounts:
                        - name: web-content
                          mountPath: /usr/share/nginx/html/index.html
                          subPath: index.html
                  volumes:
                    - name: web-content
                      configMap:
                        name: nginx-index

          # 4) NodePort Service
          - apiVersion: v1
            kind: Service
            metadata:
              name: nginx
              namespace: aap-deploy
            spec:
              type: NodePort
              selector:
                app: nginx
              ports:
                - name: http
                  port: 80
                  targetPort: 80
                  nodePort: 30080   # optional; must be within 30000–32767
        
          # create an ingress resource instead of NodePort service
          - apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: nginx-ingress
              namespace: aap-deploy
              #annotations:
              #  nginx.ingress.kubernetes.io/rewrite-target: /
            spec:
              rules:
                - host: demo.itssoltutions.me
                  http:
                    paths:
                      - path: /
                        pathType: Prefix
                        backend:
                          service:
                            name: nginx
                            port:
                              number: 80  


